### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_stemp_abw#72] opened 2019-08-06 09:37 UTC
Text is prepared by @Stefanie08 in
https://github.com/rl-institut/WAM_APP_stemp_abw/tree/feature/multi_language_support

@4lm What options do we have to implement multi-language support?

**Comment by 4lm** [comment] 2019-08-06 09:49
Thanks for the task, I like :smiley_cat: As spoken f2f - I will have a look and report!

**Comment by 4lm** [comment] 2019-08-07 17:01
Hi @nesnoj,

multi-language works! In templates and views (also in the Charts :rocket:). I had to do some workarounds, because multi-language support is normally tied as global state to `wam/settings.py`.
But we want each app to have a separate language state, so we are missing some features, which is OK IMO. The stuff we need is there!

I added a simple version with a (unstyled) language switcher in the navbar: https://github.com/rl-institut/WAM_APP_stemp_abw/commit/031e415f6cf37e8680ecc8a3f9ceff0ceb6c9215

To test it out you have to add _locale_ as middleware in `wam/settings.py`:

```
MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    ...
]
```

The last problem are the labels and texts in the config files in `stemp_abw/config`. They are set right at the beginning when the app server of the WAM is started. So right now it's not possible to set the language at runtime, load the appropriate config files with the appropriate language and reload the page or go to an app via link. That's why we always have to restart the server, when we change some stuff in the config files ...

Maybe I find a doable solution for the config files tomorrow ...

**Comment by nesnoj** [comment] 2019-08-14 10:00
As agreed yesterday f2f, you create a draft to find out if all language-related parts can be covered.
Let me know if you need a review..

**EDIT:**
BTW: In the end, pls add deployment instructions to the [dev docs](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/feature/multi_language_support/doc/developer.rst).

**Comment by 4lm** [comment] 2019-08-15 16:21
Hi @nesnoj,

enabling I18N in stemp_abw is as good as done. As far as I can see, there are only some minor things left to do (e. g. the `unit` attributes in `stemp/abw/layers_region.cfg` and `temp/abw/layers_region.cfg` are in German and should also be translatable).

In the end I opted for the `.cfg`- and `.md` files to use the approach you first suggested. I did this, because it was way less work, than changing the code to go the locale `.po` files route all the way.

So, the way to add a language to stemp_abw is relatively simple now: 

1. Make a new locale folder with .po file via `python manage.py` message commands in the desired language
2. Copy all .cfg and .md files and folders from a given locale language folder to the folder from the step before 
3. Translate
4. Add the language name as string to the `LANGUAGE_STORE` list in `app_settings` of stemp_abw. This will also automatically add the language to the language switcher.

Next week, I can explain this approach in more detail f2f, if you like.

**Comment by nesnoj** [comment] 2019-08-16 07:22
Sounds great, looking forward! :)

**Comment by nesnoj** [comment] 2019-08-23 09:27
Good work @4lm!
I merged your PR #76.

There're some shortcomings, I'd be very happy if you could tackle them:
1. The result chart tooltips (texts below the charts) are not translated. They are loaded correctly [here](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/6963f569a13675715bed18c8f025f1738161873a/results/results.py#L499) but the class `ResultChart` is instantiated by each chart only once: at the start of the app in [`result_charts.py`](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/6963f569a13675715bed18c8f025f1738161873a/results/result_charts.py). Hence, the current locale texts are not loaded again. For the very same reason, you used callables in app_settings, I think this could be fixed the very same way here..
2. I don't like the redundant layer files (`layers_*.cfg`) for each language, but I guess the units are the only reason y u opted for separate en files? What about moving the units to the labels file?
3. There're no translation for the JS files (e.g. for loading, leave page warning, ...). Is it a hassle to add it? I know, no template tags available.. :(
4. Warning message ("results lost..") on language switch (same as the other ones you used when switching to contect etc.)

I saw u added some structure for i18n to the [docs](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/6963f569a13675715bed18c8f025f1738161873a/doc/developer.rst), please complete this section :).

Branch [`4lm/feature/add-multi-language-support`](https://github.com/rl-institut/WAM_APP_stemp_abw/tree/4lm/feature/add-multi-language-support) is up-to-date, you can reuse it if you like...

Thanks a lot!

**Comment by nesnoj** [comment] 2019-09-02 14:31
Beside my comments above, I discovered a bug:

When switching from DE to EN, the first accordion in energy system is not expanded on startup as expected:

![image](https://user-images.githubusercontent.com/15910173/64121319-c11de700-cd9e-11e9-9842-1c7dfa55f1d2.png)

Contrary, when switching to DE, it is expanded properly..

**Comment by nesnoj** [comment] 2019-09-05 15:25
Another bug: The translation does not work on the landing page - do you know why?

**Comment by nesnoj** [comment] 2019-09-09 16:23
Also, some other translations are not loaded, e.g. in the left menu and in the result charts section..

**Comment by 4lm** [comment] 2019-09-12 14:30
For the record, all the i18n related issues have been fixed in branch 4lm/feature/add-multi-language-support - hopefully :wink:

I will tackle now: 

- https://github.com/rl-institut/WAM_APP_stemp_abw/issues/72#issuecomment-527168230
- >Warning message ("results lost..") on language switch (same as the other ones you used when switching to contect etc.)
- >I saw u added some structure for i18n to the docs, please complete this section :).
- Docs, Docs, Docs #30, #77 

And if there is time:
- >I don't like the redundant layer files (layers_*.cfg) for each language, but I guess the units are the only reason y u opted for separate en files? What about moving the units to the labels file?

@nesnoj, I will do a pull request for 4lm/feature/add-multi-language-support and work on the above mentioned issues in another feature branche(s).

**Comment by 4lm** [comment] 2019-09-12 14:40
>There're no translation for the JS files (e.g. for loading, leave page warning, ...). Is it a hassle to add it? I know, no template tags available.. :(

@nesnoj, I did some changes in https://github.com/rl-institut/WAM_APP_stemp_abw/pull/88/commits/bb612dbeb11ed432272629ac06fb06d79b9cf707 and https://github.com/rl-institut/WAM_APP_stemp_abw/pull/88/commits/cc6f7dbf893bfe6324496e395619d81c0279ccb3 to fix this. Do you see another section in the code where this is needed. The approach I used is not optimal and should be refactored in the future.

**Comment by nesnoj** [comment] 2019-09-13 08:07
Looks good, thx!
The only remaining tasks are
> When switching from DE to EN, the first accordion in energy system is not expanded on startup as expected:

Do you have an idea why this happens?

And the docs

**Comment by nesnoj** [comment] 2019-09-13 08:23
> @nesnoj, I will do a pull request for 4lm/feature/add-multi-language-support and work on the above mentioned issues in another feature branche(s).

:+1:

**Comment by nesnoj** [comment] 2019-09-18 09:38
@4lm **Urgent:**
I just deployed the app on WAMdev. When hitting "OK" after selecting a language, the redirect does not work correctly: I'm always redirected to the root (landing page) of the WAM instead of staying on the current page. There's a specific [order in which Django tries to redirect](https://django-book.readthedocs.io/en/latest/chapter19.html#the-set-language-redirect-view) when using the `set_language()`view (that u used).
Strangely, it works perfectly fine in my local environment.

**Comment by 4lm** [comment] 2019-09-19 10:01
@nesnoj, I think I see the problem, will do fix a branch!

**Comment by 4lm** [comment] 2019-09-19 10:52
@nesnoj, I also can't locally reproduce this issue, can you test if this commit https://github.com/rl-institut/WAM_APP_stemp_abw/commit/2e4acba59c9f902801bc1b475af050277148fb08 on branch 'fix/broken-language-support` fixes the issue. The stemp_abw app now also uses 'de-DE' as language definition and in locale instead of just 'de'.

**Comment by nesnoj** [comment] 2019-09-19 12:33
Ok, will test now

**Comment by 4lm** [comment] 2019-09-19 12:37
@nesnoj, I added a language switch confirm, which is only active in the map view, but not on the start page https://github.com/rl-institut/WAM_APP_stemp_abw/commit/4d1d3fd6b8635d0f9d74f4f32a777697d1784cec. The code also has all commits from #93, so please review this pull request first. Will also do a pull request for this one.

Edit: Pull request for this one is #94

**Comment by nesnoj** [comment] 2019-09-19 14:00
Both merged and dev deployed on WAMdev
Still redirecting to WAM landing page... :(

**Comment by 4lm** [comment] 2019-09-19 14:09
Mhh, Ok, will have a look ...

**Comment by nesnoj** [comment] 2019-09-19 14:29
Locale Middleware [moved](https://github.com/rl-institut/WAM/commit/c84b787b62c7ac71b2a1e4e274234206df98e679) as you proposed.
Same result..

**Comment by nesnoj** [comment] 2019-09-19 14:31
Maybe it's something with the webserver - caddy behaves differently than Django's (gunicorn?)
May try to set a redirect target explicitly to avoid the fallback mentioned above..

**Comment by 4lm** [comment] 2019-09-19 15:27
@nesnoj, can you test if this commit https://github.com/rl-institut/WAM_APP_stemp_abw/commit/6e5f7c7c3fff5c5559c29807affe1e3195f84ebc fixes it, the code is on branch `fix/redirect-issue`: https://github.com/rl-institut/WAM_APP_stemp_abw/tree/fix/redirect-issue.

**Comment by nesnoj** [comment] 2019-09-19 15:33
Works out!! :tada: :tada: :tada: :rocket: 

Can you crate a PR (just for the log)

**Comment by nesnoj** [comment] 2019-09-19 15:50
> Can you crate a PR (just for the log)

I'll do it
thx for this important fix

**Comment by 4lm** [comment] 2019-09-19 15:52
:tada: :tada: :tada: Cool :sunglasses:

**Comment by 4lm** [comment] 2019-09-19 15:53
Here comes the next PR, I fixed the accordion #97. This one was easy :wink:

**Comment by nesnoj** [comment] 2019-09-19 16:20
ooops

**Comment by nesnoj** [comment] 2019-09-19 16:39
@4lm Last remaining task: docs

**Comment by nesnoj** [comment] 2019-09-26 15:55
Can u finish this one today too?

**Closed as completed** 2019-10-07 00:04 UTC
Labels: enhancement
